# DataSource Config
spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #url: jdbc:p6spy:mysql://192.168.1.106:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:p6spy:mysql://172.16.83.89:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  freemarker:
    settings:
      classic_compatible: true #处理空值
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: 172.16.83.89
    port: 6379
    password:
  data:
    elasticsearch:
      cluster-name: es_sz
      cluster-nodes: 172.16.83.89:9300
      repositories:
        enabled: true
  rabbitmq:
    username: root
    password: 123456
    host: 172.16.83.89
    port: 5672
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
file:
  upload:
    dir: ${user.dir}/upload
im:
  server:
    port: 9326